# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tkellem}
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brian Palmer"]
  s.date = %q{2011-06-14}
  s.default_executable = %q{tkellem}
  s.email = %q{brian@codekitchen.net}
  s.executables = ["tkellem"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "bin/tkellem",
    "debian/changelog",
    "debian/compat",
    "debian/control",
    "debian/copyright",
    "debian/docs",
    "debian/examples",
    "debian/install",
    "debian/manpages",
    "debian/rules",
    "debian/source/format",
    "debian/tkellem.1",
    "examples/config.yml",
    "lib/tkellem.rb",
    "lib/tkellem/bouncer.rb",
    "lib/tkellem/bouncer_connection.rb",
    "lib/tkellem/daemon.rb",
    "lib/tkellem/irc_message.rb",
    "lib/tkellem/irc_server.rb",
    "lib/tkellem/migrations/001_init_db.rb",
    "lib/tkellem/migrations/002_at_connect_columns.rb",
    "lib/tkellem/models/host.rb",
    "lib/tkellem/models/listen_address.rb",
    "lib/tkellem/models/network.rb",
    "lib/tkellem/models/network_user.rb",
    "lib/tkellem/models/user.rb",
    "lib/tkellem/plugins/backlog.rb",
    "lib/tkellem/plugins/push_service.rb",
    "lib/tkellem/socket_server.rb",
    "lib/tkellem/tkellem_bot.rb",
    "lib/tkellem/tkellem_server.rb",
    "lib/tkellem/version.rb",
    "resources/bot_command_descriptions.yml",
    "spec/irc_message_spec.rb",
    "spec/irc_server_spec.rb",
    "spec/spec_helper.rb",
    "tkellem.gemspec"
  ]
  s.homepage = %q{http://github.com/codekitchen/tkellem}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{IRC bouncer with multi-client support}
  s.test_files = [
    "spec/irc_message_spec.rb",
    "spec/irc_server_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<tkellem>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.5"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_runtime_dependency(%q<eventmachine>, [">= 0"])
    else
      s.add_dependency(%q<tkellem>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.5"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<eventmachine>, [">= 0"])
    end
  else
    s.add_dependency(%q<tkellem>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.5"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<eventmachine>, [">= 0"])
  end
end

