# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tkellem}
  s.version = "0.7.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brian Palmer"]
  s.date = %q{2010-11-18}
  s.default_executable = %q{tkellem}
  s.email = %q{brian@codekitchen.net}
  s.executables = ["tkellem"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/tkellem",
    "examples/config.yml",
    "lib/tkellem.rb",
    "lib/tkellem/backlog.rb",
    "lib/tkellem/bouncer.rb",
    "lib/tkellem/bouncer_connection.rb",
    "lib/tkellem/irc_line.rb",
    "lib/tkellem/irc_server.rb",
    "spec/spec_helper.rb",
    "tkellem.gemspec"
  ]
  s.homepage = %q{http://github.com/codekitchen/tkellem}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{IRC bouncer with multi-client support}
  s.test_files = [
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0"])
  end
end

