Document: tkellem
Title: Debian tkellem Manual
Author: <insert document author here>
Abstract: This manual describes what tkellem is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tkellem/tkellem.sgml.gz

Format: postscript
Files: /usr/share/doc/tkellem/tkellem.ps.gz

Format: text
Files: /usr/share/doc/tkellem/tkellem.text.gz

Format: HTML
Index: /usr/share/doc/tkellem/html/index.html
Files: /usr/share/doc/tkellem/html/*.html
